volume up: key(volup)
volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
(volume | media) mute: key(mute)
media next: key(next)
media previous: key(prev)
media play: key(alt-cmd-ctrl-shift-f5)
media pause: key(alt-cmd-ctrl-shift-f4)
